// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1OrUsdoqGcmQ96cB-Zg--Fy6Gn9BHQZk',
    appId: '1:252509313072:web:3b1fcab3efeec0be91f5f5',
    messagingSenderId: '252509313072',
    projectId: 'quick-chat-flutter-e6206',
    authDomain: 'quick-chat-flutter-e6206.firebaseapp.com',
    storageBucket: 'quick-chat-flutter-e6206.appspot.com',
    measurementId: 'G-T2NS064CYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7nl-lRXmOvnv4Jz4qddSz-ZahqHG7K4Q',
    appId: '1:252509313072:android:ce0f2f356979ee0f91f5f5',
    messagingSenderId: '252509313072',
    projectId: 'quick-chat-flutter-e6206',
    storageBucket: 'quick-chat-flutter-e6206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCzYOiO0VDVWynkuv5hT-EfrQAZnKa7D0',
    appId: '1:252509313072:ios:b12eec41f46406e991f5f5',
    messagingSenderId: '252509313072',
    projectId: 'quick-chat-flutter-e6206',
    storageBucket: 'quick-chat-flutter-e6206.appspot.com',
    iosClientId: '252509313072-1rn6usjuniht0st2k33r7dkg8m8t14la.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChat',
  );
}
